### PR TITLE
make deployment callable from other scripts with callback

### PR DESCRIPTION
**Pull request by fivethreeo**
Example:

```js
gulp.task('deploy_resource', function () {

    var format = require('string-format');
    var deploy = require(path.join(
      __dirname,
      'node_modules',
      'cfn-elasticsearch-domain',
      'node_modules',
      'cfn-lambda',
      'deploy'));

    return deploy(
      'eu-west-1', ['eu-west-1'], function (res) {
          console.log(format(res, 'eu-west-1'));
      }
    );
});
```

### CODE REVIEW

**Comment by bendavis78** [comment]
+1

**Comment by fivethreeo** [comment]
Top level would make it imposdiblr to use more than one cfn. If so it would need a module arg.

**Comment by fivethreeo** [comment]
Both the 
```js
"cfn-lambda-deploy": "node ./node_modules/cfn-lambda/deploy.js"
```

and

```js

    var cfnlambda = require('cfn-lambda');
    var config = require('./config.json');
    var format = require('string-format');

    return cfnlambda.deploy(
      'cfn-elasticsearch-domain',
      'eu-west-1',
      ['eu-west-1'],
      function (res) {
          console.log(format(res, config.region));
      }
    );
```

Methods work.

**Comment by andrew-templeton** [comment]
If I drop a PR, comment again like this - I have over 25 public projects I'm sole contrib on and ~100 others I get notifs for. Chances are I liked your PR and just forgot about it :) 

Thank you much for the commits! Really good stuff / +1

**Comment by fivethreeo** [comment]
Thank you :) This module really makes cfn lamdas easy. But could you do a new release in the NOM registry? npm just wants to pull the one on there.

**Comment by andrew-templeton** [comment]
Going to release tonight

**Pull request merged**
